version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_PASSWORD: mysecurepassword
    command: ["redis-server", "--requirepass", "mysecurepassword"]
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server
    ports:
      - 4000:4000
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
      - redis
    develop:
      watch:
        - path: ./server/package*.json
          action: rebuild
        - path: ./server
          target: /app
          action: sync

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    depends_on:
      - server
    develop:
      watch:
        - path: ./frontend/package*.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

volumes:
  mongodb_data:
    driver: local
